### ISSUE TITLE
Pinky broke your module

### ISSUE THREAD

**Issue by Owyn** [teralove/parcel-helper#3]
```
ERROR tera-proxy-game: [dispatch] load: error initializing module "parcel-helper-master"
error: [dispatch] hook: version is required
    at new ParcelHelper (\Tera-Proxy\bin\node_modules\parcel-helper-master\index.js:171:14)
    at Dispatch.load (\Tera-Proxy\node_modules\tera-proxy-game\lib\connection\dispatch\index.js:147:25)
    at Dispatch.connection.dispatch.once (\Tera-Proxy\bin\lib\proxy.js:124:50)
    at Object.onceWrapper (events.js:272:13)
    at Dispatch.emit (events.js:180:13)
```

**Comment by teralove** [comment]
Updated
